<a href="https://colab.research.google.com/github/Imshyeon/2023_AI_BACKEND_AI/blob/master/09_13_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
a0 = np.array(9)
print(a0)

9


In [4]:
a1 = np.array([1,3,5,7,9])
print(a1)

[1 3 5 7 9]


In [5]:
a1[2]

5

In [6]:
a1[1:3]

array([3, 5])

In [7]:
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a2[1]

array([4, 5, 6])

In [9]:
a2[1,1]

5

In [10]:
a2[:, 1]

array([2, 5, 8])

In [11]:
a3 = np.array([[[1,2],
                [3,4]],
               [[5,6],
                [7,8]],
               [[9,10],
                [11,12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [12]:
a3[1]

array([[5, 6],
       [7, 8]])

In [13]:
a3[1,1]

array([7, 8])

In [14]:
a3[1,1,1]

8

In [15]:
a3[:,0,0]

array([1, 5, 9])

In [16]:
a3[:,:,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [17]:
AR = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
AR.shape

(12,)

In [19]:
AR.ndim

1

In [20]:
AR.size

12

In [23]:
AR2 = AR.reshape(3,4)
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
AR2.shape

(3, 4)

In [25]:
AR2.ndim

2

In [26]:
AR2.size

12

In [27]:
AR3 = AR.reshape(3,2,2)
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [28]:
AR3.shape

(3, 2, 2)

In [29]:
AR3.ndim

3

In [30]:
AR3.size

12

In [31]:
AR.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [32]:
AR2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [33]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.zeros([3,4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.random.rand(3,2,2)

array([[[0.33839917, 0.3205245 ],
        [0.22010463, 0.31372472]],

       [[0.64881781, 0.92252259],
        [0.7221113 , 0.9798084 ]],

       [[0.58150104, 0.46300538],
        [0.18511986, 0.71145401]]])

In [48]:
np.random.randint(1,45,size=(5,6))

array([[32, 32, 22,  1, 30,  4],
       [42,  8,  3,  5, 10, 16],
       [40,  3, 27, 31, 11, 44],
       [18, 36,  4,  4, 22, 29],
       [25, 13, 44,  7,  9, 44]])

In [49]:
np.random.seed(2045)
np.random.choice(np.arange(1,46), size=(5,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

In [50]:
TA = np.arange(1,10)
TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.random.shuffle(TA)
TA

array([7, 6, 5, 4, 3, 1, 8, 2, 9])

In [53]:
A1 = np.array([85,93,75,97,69])
A2 = np.array([91,90,85,97,89])
A3 = np.array([[85, 93, 75],
               [90, 84, 97],
               [99, 91, 80]])

In [54]:
A1 + A2

array([176, 183, 160, 194, 158])

In [55]:
A2 - A1

array([ 6, -3, 10,  0, 20])

In [56]:
A1 * A2

array([7735, 8370, 6375, 9409, 6141])

In [57]:
A2/A1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [58]:
A1 * 3

array([255, 279, 225, 291, 207])

In [59]:
A2 ** 2

array([8281, 8100, 7225, 9409, 7921])

In [60]:
A1.sum()

419

In [61]:
A2.mean()

90.4

In [62]:
A2.var()

15.040000000000001

In [64]:
A2.std()

3.8781438859330635

In [65]:
A2.min()

85

In [66]:
A3.min()

75

In [67]:
A3.min(axis=0)

array([85, 84, 75])

In [68]:
A3.min(axis=1)

array([75, 84, 80])

In [69]:
A3.min(axis=1, keepdims=True)

array([[75],
       [84],
       [80]])

In [70]:
A2.max()

97

In [71]:
A3.max()

99

In [72]:
A3.max(axis=0)

array([99, 93, 97])

In [73]:
A3.max(axis=1)

array([93, 97, 99])

In [74]:
A3.max(axis=1, keepdims=True)

array([[93],
       [97],
       [99]])

In [75]:
A1.cumsum()

array([ 85, 178, 253, 350, 419])

In [76]:
A1.cumprod()

array([        85,       7905,     592875,   57508875, 3968112375])

In [77]:
M1 = np.array([2,4,6,8]).reshape(2,2)
print(M1)
M2=np.array([3,5,7,9]).reshape(2,2)
print(M2)

[[2 4]
 [6 8]]
[[3 5]
 [7 9]]


In [78]:
M1.dot(M2)

array([[ 34,  46],
       [ 74, 102]])

In [79]:
np.dot(M2,M1)

array([[ 36,  52],
       [ 68, 100]])

In [80]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [81]:
M2 * M1

array([[ 6, 20],
       [42, 72]])

In [82]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

In [83]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [84]:
M2.T

array([[3, 7],
       [5, 9]])